### ISSUE TITLE
RuntimeError: Mask Type should be defined

### ISSUE THREAD

**Issue by code-with-roz** [UBC-NLP/afrolid#1]
#### Description
Hi, I get this error when I try to run the AfroLID code that integrates it with pandas. When I troubleshoot they say the main reason could be data type incompatibility between the input and output data, but I've made sure the input data is a string type. Could it be because AfroLID doesn't recognise the  language being input? I'm using South African tweets that are sometimes a mix of English and other local languages. Although, I also get the same error when working with purely Swahili tweets. Please help. 

#### Screenshots
![Error](https://user-images.githubusercontent.com/85030845/221359523-a05c5031-bfb4-45cd-8d09-9b7ffdff2ed1.PNG)

#### Files
[Integrate AfroLID with Python code](https://afrolid.readthedocs.io/en/latest/Integrate_afrolid_with_your_code.html)

#### To Reproduce
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
df = pd.read_csv(filename)

def get_afrolid_prediction(text):
      predictions = cl.classify(text, max_outputs=1)
      for lang in predictions:
            return lang, predictions[lang]['score'], predictions[lang]['name'], predictions[lang]['script']

df['predict_iso'], df['predict_score'], df['predict_name'], df['predict_script'] = zip(*df['Text'].progress_apply(get_afrolid_prediction))

**Comment by elmadany** [comment]
Thanks, @code-with-roz for reaching out.
Could you please use this colab
[https://colab.research.google.com/github/UBC-NLP/afrolid/blob/main/examples/Integrate_afrolid_with_your_code.ipynb](https://colab.research.google.com/github/UBC-NLP/afrolid/blob/main/examples/Integrate_afrolid_with_your_code.ipynb)

**Comment by code-with-roz** [comment]
Great! It works. Running the code from the actual notebook instead of transferring the code into my notebook did the trick.  Thank you!
